<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wel_BasicInfoTitle</name>
   <tag></tag>
   <elementGuidId>2585ad17-e3f9-4a5a-8a0a-8d6da0ea6bc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id = 'ctl00_ctl00_MasterPageContent_MainContent_lblBasicInfo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_MasterPageContent_MainContent_lblBasicInfo</value>
   </webElementProperties>
</WebElementEntity>
