<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Coverages</name>
   <tag></tag>
   <elementGuidId>268ac877-a611-4782-b1a8-dbdea4a23a26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ctl00_MasterPageContent_MainContent_grdVehicle_ctl00_ctl06_btnVehicleCoverages']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
