<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_Rehabilitation</name>
   <tag></tag>
   <elementGuidId>8cafb188-b3bc-4676-a291-98df87385c55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='radio'][@fieldref='UnderwritingQuestionsInput.RehabilitationOrRenovation'][@value='0']
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
