<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drp_PlantsShrubsandTrees</name>
   <tag></tag>
   <elementGuidId>e68d6d9e-d422-4a09-a16a-34e38329bf65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@fieldref='PlantsShrubsAndTreesInput.PlantShrubsAndTreesIndicator']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
