<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>BillingFlow - UAT</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>df1d373c-9634-49c7-bf7c-23b3c1f4754b</testSuiteGuid>
   <testCaseLink>
      <guid>4dc6abe5-a387-4a31-a111-ade290f4aae2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Billing/Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bd85b56-022b-4d00-b8d8-7862d4829218</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06a5ca49-bb26-4da9-a1f8-65a99b76b2c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>048cdfd7-b816-40ce-8968-57de4fe7306c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7aec1a2b-b184-44f5-b150-e2e8ad777988</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Billing/HomePage - App03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51d8ef03-abe9-4aac-9101-ae1e88da951b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>515db779-f83a-4e46-8798-328e1f8bdf50</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Billing/AccountPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b69bda39-e121-4e35-9b7e-3bff9cc40897</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1a90789-1f49-4a20-bf24-7ac36c1d5a20</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Billing/PolicyTermSummary</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ee61f56-0887-408e-b6d2-98a7196fa1e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb9ecda0-aa6f-4660-bd79-46d25cc0397a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Billing/InstallmentSchedule</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
