<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>InstallmentScheduleValidation</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>20807721-aac7-49e9-9f5b-d267ed37e635</testSuiteGuid>
   <testCaseLink>
      <guid>64b34f95-0c56-4255-a845-d217a67f8e65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Billing/Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bd85b56-022b-4d00-b8d8-7862d4829218</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06a5ca49-bb26-4da9-a1f8-65a99b76b2c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>048cdfd7-b816-40ce-8968-57de4fe7306c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>013ceeab-edf4-4ad3-b155-af983f29d6c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Billing/HomePage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5a25e38-ba02-4a07-be04-53f2e19b27d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9cbcfa04-d2a5-4f4b-b1fb-0021972dfd00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Billing/AccountPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b69bda39-e121-4e35-9b7e-3bff9cc40897</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a733b74-f138-4768-a311-a6376ac58e0a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Billing/PolicyTermSummary</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ee61f56-0887-408e-b6d2-98a7196fa1e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f3ce795-ab0b-46cb-9761-183abd040afe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Billing/InstallmentSchedule</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>948247f0-33f2-4ac6-a68e-bfcf0d8c318e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Billing/TermPlan</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c1abb3f-f2e9-4950-80f2-3328b9341318</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>529756c8-7408-4c9d-a0fd-90ba082b23d7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
