<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_PageTitle</name>
   <tag></tag>
   <elementGuidId>18ec60db-ce54-49e3-a94c-34ca6bca5d41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'applicationName']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='applicationName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdc193a5-26fc-4be8-a833-2fee29ed6525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>applicationName</value>
      <webElementGuid>862467f2-3c9c-4b33-99b1-cf9bc6440c67</webElementGuid>
   </webElementProperties>
</WebElementEntity>
