<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Roomsaffected</name>
   <tag></tag>
   <elementGuidId>3edf9893-01df-4ba0-9ad3-3f6d20abfc90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_MasterPageContent_MainContent_dgphDetails_KeyFactCstm__DIc56426dccae4d4e98f47ac67c0eba8_Input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
