<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ReportedBy</name>
   <tag></tag>
   <elementGuidId>2800c4a7-ad5d-4da1-99a4-99a662daf913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @id = 'ctl00_ctl00_MasterPageContent_MainContent_cboReportedBy_Input']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_MasterPageContent_MainContent_cboReportedBy_Input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edf88e95-5733-4902-92fc-8125af98a37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97bdfb27-4a83-4d0e-a3e5-affe3809507e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_MasterPageContent_MainContent_cboReportedBy_Input</value>
      <webElementGuid>c09a3ab0-02a6-4ecb-a246-d2384594597f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
