<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Smoke Test - Internal User - without brokerage</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8ca6c700-fba2-4b95-9136-b04837d71e00</testSuiteGuid>
   <testCaseLink>
      <guid>f1389d13-bd3b-45d8-b501-fca57dd7ff27</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/Login/InternalUserLogin - Without Brokerage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>976a26de-7721-4192-b756-b581476e5422</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/NewQuote - NoBroker NewProduct</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a684f23a-2311-41e8-8a0a-c4a2800debfa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62e9e085-456c-430e-ad1d-25f2a33a0a97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/SkipQuickQuote</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c42d5f42-4cdd-4264-81a0-19dca877abac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/Applicant</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>714accfb-3626-4ff1-a06d-0388f9eb7ebe</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData/SmokeTest</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>714accfb-3626-4ff1-a06d-0388f9eb7ebe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>EntityType</value>
         <variableId>717b89d0-1609-48d3-9cf7-fcba321bd5ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>714accfb-3626-4ff1-a06d-0388f9eb7ebe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>EntityName</value>
         <variableId>7a98e92e-8ccd-4d43-bcc9-88e317825bcb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>714accfb-3626-4ff1-a06d-0388f9eb7ebe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ApplicantFName</value>
         <variableId>d2d0f84a-6230-42da-b17c-09143156b8fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>714accfb-3626-4ff1-a06d-0388f9eb7ebe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ApplicantLName</value>
         <variableId>4fb6fde3-1635-4169-9869-3cc08844418e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>714accfb-3626-4ff1-a06d-0388f9eb7ebe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PrimaryPhone</value>
         <variableId>66a108f5-0b2b-4e5d-afcb-b9b99f245a4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>714accfb-3626-4ff1-a06d-0388f9eb7ebe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ApplicantAddress1</value>
         <variableId>37e08132-8474-4188-8898-b46bad53373d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>714accfb-3626-4ff1-a06d-0388f9eb7ebe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ApplicantCity</value>
         <variableId>b82f42ff-1b33-4798-a22b-3ad65f368ebc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>714accfb-3626-4ff1-a06d-0388f9eb7ebe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ApplicantZip</value>
         <variableId>8703e158-13de-4801-b801-e51cb8448c50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>714accfb-3626-4ff1-a06d-0388f9eb7ebe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>SecondaryEntityType</value>
         <variableId>1b100f39-48ab-4f2d-9b1b-fa89e56cd5f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>714accfb-3626-4ff1-a06d-0388f9eb7ebe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>SecondaryFName</value>
         <variableId>2c7d1c11-2db2-4a71-adfd-2034d3ca5396</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>714accfb-3626-4ff1-a06d-0388f9eb7ebe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>SecondaryLName</value>
         <variableId>b5dc6080-41d1-40ea-9f94-171ca97e536a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93659231-3793-4c3b-9766-14db4b1c2ced</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/PolicyTerm - New</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d441abf-4f9b-4ed2-8441-a6d7159a6836</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba9c986d-ebaf-4767-9e0e-fb17b2c821d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b9122de-312b-4788-8571-9c154c970878</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27902637-9107-4c3b-820f-7e4301d22c94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/DwellingInformation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>eacd3299-f994-45a0-b4ec-29613337908f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/DwellingCoverage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2b41ee92-d158-4540-aab9-6c8b7a87af70</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/AdditionalInterest</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>00348d02-a5fb-49ed-9761-adbc32252b8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/Underwriting</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9d12d2c1-27e8-44fb-8c2c-3aef7c451b2a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/InsuranceHistory</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3ce5389c-da43-446f-b48a-aa05a0e18de7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData/SmokeTest</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>175090bd-0fda-47e6-bcec-ba7c7ca1e5d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00b32916-6a97-4f12-8444-1f958916cb1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba4d5a73-56df-48af-b785-002d831532a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfa1efa8-551d-4969-8df6-b28bbe3c089e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>faa34396-191d-45f4-9f11-7a8a643815ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f95fa6a5-1179-4f06-902b-44dda4f8c3e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/LossHistory</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>094792b1-3f0a-440c-af9d-a5444c0be2fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/Pricing - New</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94da4ffe-52e5-48a9-b571-0054b4fda876</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>093daf93-7d77-4547-b0d9-10ff5a06a841</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dab5684b-14ef-4284-ae42-33ff33a163ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c270d33-a8a1-4851-bd0a-a1b67f6752ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07805019-522b-4b76-a418-3211f42db967</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/Transact</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62b5b4cd-c664-4856-b86e-80ffa4969bb4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f1ee03cc-cae2-45c3-8ce5-de59646c1b3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/ApplicantInformation_PolicyApprove</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>62e098c0-9d55-4818-9327-09ae94a15869</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/PolicyTerm_PolicyApprove</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a57113fa-49a4-4f20-afa9-4eec32b71a43</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/DwellingInformation_PolicyApprove</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f8776b7f-d706-4b32-8b9a-e740b21a56f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/Pricing_PolicyApprove</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff04c3e2-d332-424b-b502-2166cb7596d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b74aedaa-c476-48da-92bd-575f07a73ce9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>baf6d56f-a873-4d37-877d-9dd1a71662b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>766b3d58-0ed6-4e26-8c1d-b55def45d4d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f6024e0-40b4-4868-8557-26aaddbd0636</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/Transact_PolicyApprove</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d073030d-5365-4c8b-9f2d-518a7ccb0246</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5327157d-cdf9-4558-8bc2-842211b9f0e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f88f9ce9-e497-4b9e-b1c6-d93022905044</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e93bf16-07ef-4777-979c-e82041bd43bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7a9b2dd-19f2-4409-a3f8-22cfaea6d58a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5661a4a1-023c-4325-a360-a0379c6e86c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/Login/InternalUserLogin - Without Brokerage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>16791102-4ec4-47d4-9d2a-1461e9ae0f57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/CEA/NewQuote_CEA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>232e252c-40bd-4289-b33b-69177cf78160</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a0c4298-7d24-4386-8533-5c695285f621</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4be86350-386e-43cf-9e7e-402028264c29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/CEA/Applicant_CEA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>148fcac8-ea7a-451d-a502-ab6983ed54d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/CEA/PolicyTerm_CEA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c01a9b4b-3c3a-4654-b385-a4f6f65e7b65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/CEA/DwellingInformation_CEA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3293cec4-b65c-41d4-90b2-d5cfe98905fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b5322e6-361e-4c53-970f-2cacf92f57bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58abd2c5-59ea-4f7b-876d-f0214dc5bd69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28fb1aa9-46ad-4873-ba61-975109b409fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c336bf6e-7cfd-4641-9c0e-e47ba4a0fd3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df420ac4-fd6b-405a-98b0-6faab44465a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c561be6-75b4-4904-82d0-da2ec32f31d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>665bdfa1-1db9-4621-8d16-da27ea62448e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b017f871-cbb0-4086-a7f7-0a36fda2fa53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c46f64c6-90a8-41ee-ad62-02ee5a48cd81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63f3e371-28da-4388-b70c-596d428f724a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a420e89-6657-4906-9c3c-19bbdd9f394c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>717f8bbe-54b9-4c4a-821d-748240f055e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/CEA/DwellingCoverage_CEA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37d508c9-5228-485f-af24-88ad9ff56494</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bf0d40e-7011-4298-b37a-77ec246c2f46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2888144-a6bc-416c-a62f-355f36d56d55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea6fc962-dd16-4925-bcd7-7fecab710fdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c02d9227-a639-4e2a-b2b4-c89e36a71c17</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7a323946-9659-444e-8cba-76862a931f7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/AdditionalInterest</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f99663bb-ef85-42e0-85a0-242a592ec82a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/CEA/Pricing_CEA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6704879-bcfb-4b81-a034-63cf4b31858f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8883d67c-5464-45f2-a6b0-0664fe0ef2ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>74365f43-e98e-434b-a58c-4e9c7b29a9f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/Transact</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62b5b4cd-c664-4856-b86e-80ffa4969bb4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d57ee6b4-9e60-48c6-ba26-e7adbf3df590</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/ApplicantInformation_PolicyApprove</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5c92c233-3f28-44ec-80de-2ca962065c57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/CEA/PolicyTerm_PolicyApprove_CEA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d5440b34-f322-4ec1-bfc5-7c7b09b9298b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/CEA/DwellingCoverage_PolicyApproveCEA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>76bbf287-067c-45dd-ace6-a456eee9f7d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/CEA/Pricing_PolicyApproveCEA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40a1f3b5-68ed-4961-bfc2-8a7541348c76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c4e35b2c-c526-4377-b244-6cd1ace69395</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Policy/CEA/Transact_PolicyApprove_CEA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aeb30e53-75d6-4f10-bca6-ed6cd958e84d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>296bf6c4-7921-4ea3-af7e-aea46c44fda3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a1e1967-ed48-44f3-90a3-8a571d20ce2a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
