<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_SubstandardQuestion1</name>
   <tag></tag>
   <elementGuidId>72785582-c987-4a34-9e52-2d78a609a09a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@fieldref='EligibilityOrRatingQuestionsInput.FencesGuttersExteriorFixturesQuestion'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
