<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_PropertyUnhabitable</name>
   <tag></tag>
   <elementGuidId>f329c9b5-306e-4d9b-b124-60b59cf59d9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='radio'][@fieldref='EligibilityOrRatingQuestionsInput.EligibilityRatingQuestion1'][@value='0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
