<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rb_EligibilityRating10</name>
   <tag></tag>
   <elementGuidId>fe2462b9-0055-452b-81fa-c4a257a87bd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@fieldref='EligibilityOrRatingQuestionsInput.MissingExteriorDoorsWindowQuestion'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
