<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rb_EligibilityRating4</name>
   <tag></tag>
   <elementGuidId>a9606988-0419-44d2-b394-0a374d03c93c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@fieldref='EligibilityOrRatingQuestionsInput.EligibilityRatingQuestion13'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
