<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rb_RatingQuestion6</name>
   <tag></tag>
   <elementGuidId>37b2cde6-4458-4aed-bfaa-3164d11005d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@fieldref='EligibilityOrRatingQuestionsInput.EligibilityRatingQuestion11'])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
