<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rb_RatingQuestion7</name>
   <tag></tag>
   <elementGuidId>e87db34a-f6be-4b66-8c7c-0abf0c1a20d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@fieldref='EligibilityOrRatingQuestionsInput.EligibilityRatingQuestion12'])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
